import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>튼튼마디 한의원 부산서면점</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
